# Generated by Django 4.1.2 on 2022-10-24 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_temporder_qayerdan_alter_temporder_qayerga'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
