# Generated by Django 4.1.2 on 2022-10-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_order_create_date_order_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveorder',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archiveorder',
            name='create_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
