# Generated by Django 4.1.2 on 2022-10-24 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_archiveorder_create_date_archiveorder_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporder',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='temporder',
            name='create_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
