# Generated by Django 4.1.2 on 2022-10-24 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_temporder_create_date_temporder_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveorder',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='archiveorder',
            name='create_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
