# Generated by Django 4.1.2 on 2022-10-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_archiveorder_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveorder',
            name='price',
            field=models.CharField(default=100000, max_length=200),
        ),
    ]
